---
default: --profile local
local:
  SYSTEM_OF_RECORD_API_URL='http://0.0.0.0:8000'
  MINT_API_URL='http://0.0.0.0:8001'
  PROPERTY_FRONTEND_URL='http://0.0.0.0:8002'
  SEARCH_API_URL='http://0.0.0.0:8003'
  CASEWORK_FRONTEND_URL='http://0.0.0.0:8004'
  PUBLIC_TITLES_API_URL='http://0.0.0.0:8005'
  SERVICE_FRONTEND_URL='http://0.0.0.0:8007'
  DECISION_URL='http://0.0.0.0:8009'
  --format pretty
devenv:
  SYSTEM_OF_RECORD_API_URL='http://system-of-record.landregistry.local'
  MINT_API_URL='http://mint.landregistry.local'
  PROPERTY_FRONTEND_URL='http://property-frontend.landregistry.local'
  SEARCH_API_URL='http://search-api.landregistry.local'
  CASEWORK_FRONTEND_URL='http://casework-frontend.landregistry.local'
  PUBLIC_TITLES_API_URL='http://public-titles-api.landregistry.local'
  SERVICE_FRONTEND_URL='http://service-frontend.landregistry.local'
  DECISION_URL='http://decision.landregistry.local'
  --format pretty
heroku:
  SYSTEM_OF_RECORD_API_URL='http://lr-system-of-record.herokuapp.com'
  MINT_API_URL='http://lr-mint.herokuapp.com'
  PROPERTY_FRONTEND_URL='http://lr-property-frontend.herokuapp.com'
  SEARCH_API_URL='http://lr-search-api.herokuapp.com'
  CASEWORK_FRONTEND_URL='http://lr-casework-frontend.herokuapp.com'
  PUBLIC_TITLES_API_URL='http://lr-public-titles-api.herokuapp.com'
  SERVICE_FRONTEND_URL='http://lr-service-frontend.herokuapp.com'
  DECISION_URL='http://lr-decision.herokuapp.com'
  --format progress

